### ISSUE TITLE
Possible weird edge case

### ISSUE THREAD

**Issue by prabhuteja12** [hide-org/hide-sdk#22]
Hello! 

```
hc.delete_file(project.id, hc.list_files(project.id)[0])
```
throws up an error that 

```
hide.client.hide_client.HideClientError: file path='/something' not found
```

But
```
hc.delete_file(project.id, hc.list_files(project.id)[0].path[1:])
```
works by stripping the leading slash. 

Is this intended behaviour?

**Comment by artmoskvin** [comment]
Hey! I think it's a bug. I'll take a look at it.

**Comment by artmoskvin** [comment]
The bug was in the list files endpoint. The paths should be relative. Fix is on the way https://github.com/hide-org/hide/pull/113

**Comment by artmoskvin** [comment]
Just checked by myself and realised that `delete_file` expected file path instead of a `File` or `FileInfo` returned by `list_files`. Opened a PR to allow passing both of them.

**Comment by artmoskvin** [comment]
#23 is merged now. The `delete_files` method supports passing a `model.File` instance.
