### ISSUE TITLE
Bug in toolkit -- missing `timeout`

### ISSUE THREAD

**Issue by prabhuteja12** [hide-org/hide-sdk#29]
Hello, 

Looking at the code in [toolkit.py](https://github.com/hide-org/hide-sdk/blob/main/hide/toolkit/toolkit.py#L25C9-L25C16), I see that the `timeout` argument is not passed down to the `self.client.run_task` in Line 33. Can you please look into fixing this?

Thank you!

**Comment by artmoskvin** [comment]
Hello! Thanks for reporting! We somehow overlooked it. I would really appreciate if you could open a PR fixing this. Otherwise either me or @aleh-null will fix this later today.

**Comment by prabhuteja12** [comment]
Hello, created #30 to fix this. Let me know if that's fine.

**Comment by artmoskvin** [comment]
@prabhuteja12 Thank you! It's perfect and I merged it. Congrats on your first contribution! The new sdk version (0.5.2) should be available in PyPi now.
